---

# The play operates on the local (Ansible control) machine.
- name: Provision instance
  hosts: local
  connection: local
  gather_facts: True

  vars:
    key_pair_name: vyos-build-ami
    key_pair_file: "files/ssh-keys/{{ key_pair_name }}.pem"

    security_group_name: vyos-build-ami

    image_id: ami-808675f7 # Ubuntu Server 12.04 LTS (PV) - Free tier eligible
    instance_type: t1.micro # Free tier eligible
    volume_size: 4 # GB

  tasks:
    # ---- Configure AWS account ----
    - name: Make sure that files/ssh-keys directory exists
      file: path=files/ssh-keys state=directory

    - name: Create an SSH key pair
      shell: aws ec2 create-key-pair
             --key-name {{ key_pair_name }}
             --query 'KeyMaterial' > {{ key_pair_file }}
             creates={{ key_pair_file }}

    - name: Change permissions on {{ key_pair_file }}
      file: path={{ key_pair_file }} mode=0400

    - name: Create a security group
      command: aws ec2 create-security-group
               --group-name {{ security_group_name }}
               --description "This security group was generated by ansible playbook vyos_build_ami.yml"

    # Restrict the security group inbound IP address to ansible control machine?
    - name: Add a rule to the security group that allows inbound SSH traffic
      command: aws ec2 authorize-security-group-ingress
               --group-name {{ security_group_name }}
               --protocol tcp
               --port 22
               --cidr 0.0.0.0/0

    # ---- Launch EC2 instance ----
    - name: Launch an EC2 instance {{ image_id }} {{ instance_type }}
      command: aws ec2 run-instances
               --image-id {{ image_id }}
               --key-name {{ key_pair_name }}
               --security-groups {{ security_group_name }}
               --instance-type {{ instance_type }}
               --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"DeleteOnTermination":"true","VolumeType":"standard"}},{"DeviceName":"/dev/sdf","Ebs":{"VolumeSize":{{ volume_size }},"DeleteOnTermination":"true","VolumeType":"standard"}}]'
               --query 'Instances[*].InstanceId'
      register: instance_id

    - name: Wait for the instance to enter the "running" state
      command: aws ec2 describe-instances
               --instance-id {{ instance_id.stdout }}
               --query 'Reservations[*].Instances[*].State.Name'
      register: instance_state
      until: instance_state.stdout != "pending"
      retries: 6
      delay: 20

    - name: Get the public IP address of the instance
      command: aws ec2 describe-instances
               --instance-id {{ instance_id.stdout }}
               --query 'Reservations[*].Instances[*].PublicIpAddress'
      register: instance_public_ip

    - name: Add instance's public IP address to ansible host group ec2
      add_host: name={{ instance_public_ip.stdout }} groups=ec2

    # - name: Get the instance's SSH host keys from console
    #   shell: aws ec2 get-console-output
    #          --instance-id i-842b35c7 | scripts/ec2-knownhost 54.72.29.205
    #          # perl -ne 'print if /BEGIN SSH .* KEYS/../END SSH .* KEYS/' | tr -d '\n\r'
    #   register: result
    #   until: result
    #   retries: 6
    #   delay: 20
    #   tags: test2

    # - debug: "var=result.stdout.startswith('ec2: -----BEGIN SSH HOST KEY FINGERPRINTS-----\r\nec2: ')"
    # - debug: var=result.stdout
    #   tags: test2

    # - name: Extract ssh host keys from console get-console-output
    #   script: scripts/ec2-knownhost {{ instance_public_ip }}

    - name: Wait for SSH to come up
      wait_for: host={{ instance_public_ip.stdout }} port=22 delay=10 state=started

    # ---- Bootstrap instance??? ----
    # Setup /etc/sudoers file for passwordless ssh sudo
